# Generated by Django 6.0.6 on 2026-06-22 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.AddField(
            model_name='order',
            name='confirmation_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم تأكيد الطلب (يحدده الأدمن)'),
        ),
        migrations.AddField(
            model_name='order',
            name='table_number',
            field=models.PositiveIntegerField(default=1, verbose_name='رقم الطاولة'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_name',
            field=models.CharField(max_length=100, verbose_name='الاسم الثلاثي'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='رقم الهاتف'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'قيد الانتظار'), ('confirmed', 'تم التأكيد'), ('delivered', 'تم التسليم'), ('cancelled', 'ملغي')], default='pending', max_length=20),
        ),
    ]
